image: golang:1.11

variables:
    GO111MODULE: "on"

stages:
    - test
    # - build

testing:
    stage: test
    script:
        - go tool vet -composites=false -shadow=true *.go
        - go test -v -cover -race ./...

# compile:
    # stage: build
    # script:
        # Better put this in a Makefile
        # - go build -race -ldflags "-extldflags '-static'" -o mybinary
    # artifacts:
        # paths:
            # - mybinary
