image: golang:latest

before_script:
    - ln -s /builds $GOPATH/src/gitlab.com
    - cd $GOPATH/src/gitlab.com/$CI_PROJECT_PATH
    - curl https://glide.sh/get | sh
    - glide install

stages:
    - test
    # - build

format:
    stage: test
    script:
        - go tool vet -composites=false -shadow=true *.go
        - go test -race $(go list ./... | grep -v /vendor/)

# compile:
    # stage: build
    # script:
        # Add here all the dependencies, or use glide/govendor/...
        # to get them automatically.
        # - go get github.com/alecthomas/kingpin
        # Better put this in a Makefile
        # - go build -race -ldflags "-extldflags '-static'" -o mybinary
    # artifacts:
        # paths:
            # - mybinary
